admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

restaurante:
    resource: "@RestauranteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
